### ISSUE TITLE
Bug in newer versions of Sublime

### ISSUE THREAD

**Issue by cory-seatsmart** [daftspunk/october-twig#3] opened 2018-05-23 18:56 UTC
I am running Sublime Text version 3.1.1 and when opening files that use this syntax highlighter, I get the following error:

`Error loading syntax file "Packages/October Twig Highlighter/october-twig.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

Is this an issue with the package or perhaps my Sublime config?

**Comment by daftspunk** [comment] 2018-05-24 04:30
We need someone to discover a way to create a simple syntax package that combines both Twig and PHP to a single parser. Since it involves merging two existing syntax packages, it doesn't seem like it should be a difficult task.

If you can find the answer, please share it with us. The problem is:

October Twig format is together

- PHP syntax; and
- Twig syntax

How do we define it like this?

**Comment by daftspunk** [comment] 2022-02-07 03:09
Fixed by #7

**Closed as completed by daftspunk** 2022-02-07 03:09 UTC
